config/routes.rb
Rails.application.routes.draw do
  get "suspensions/edit"
  get "suspensions/update"
  get "suspensions/destroy"
  scope(:path => '/anaco') do
    # 1. Routes Active Storage (montées manuellement ici) #Attention enlever match 404 si on eleve ces routes
    #scope '/rails/active_storage' do
    #  get '/blobs/redirect/:signed_id/*filename', to: 'active_storage/blobs/redirect#show', as: :rails_service_blob
    #  get '/blobs/proxy/:signed_id/*filename', to: 'active_storage/blobs/proxy#show', as: :rails_service_blob_proxy
    #  get '/blobs/:signed_id/*filename', to: 'active_storage/blobs/redirect#show'
    #  get '/representations/redirect/:signed_blob_id/:variation_key/*filename', to: 'active_storage/representations/redirect#show', as: :rails_blob_representation
    #  get '/representations/proxy/:signed_blob_id/:variation_key/*filename', to: 'active_storage/representations/proxy#show', as: :rails_blob_representation_proxy
    #  get '/representations/:signed_blob_id/:variation_key/*filename', to: 'active_storage/representations/redirect#show'
    #  get '/disk/:encoded_key/*filename', to: 'active_storage/disk#show', as: :rails_disk_service
    #  put '/disk/:encoded_token', to: 'active_storage/disk#update', as: :update_rails_disk_service
    #  post '/direct_uploads', to: 'active_storage/direct_uploads#create', as: :rails_direct_uploads
    #end

    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)
    devise_for :users, path: '',
               path_names: { sign_in: 'connexion', sign_out: 'logout' },
               controllers: { sessions: 'sessions' }

    root 'pages#index'
    get 'global_search', to: 'pages#global_search'
    get 'utilisateurs' => 'users#index'
    post 'import_users' => 'users#import'
    post '/select_nom' => 'users#select_nom'

    get 'suivi_remplissage_schemas', to: 'users#suivi_remplissage_schemas'

    resources :bops do
      resources :avis, only: [:new, :create, :edit, :update]
    end
    post 'import_bops' => 'bops#import'
    post 'filter_bop', to: 'bops#filter_bop'

    resources :missions
    resources :ministeres

    # resources :gestion_schemas, except: [:new, :create]
    resources :schemas, except: [:new, :create] do
      resources :gestion_schemas
      member do
        get 'confirm_delete' => "schemas#confirm_delete"
        get 'pdf_vision' => "schemas#pdf_vision"
      end
    end
    get 'schemas_remplissage' => "schemas#schemas_remplissage"
    get 'generate_schemas_pdf' => "schemas#generate_schemas_pdf"

    resources :programmes do
      resources :schemas, only: [:new, :create]
      member do
        get 'last_schema', to: 'programmes#show_last_schema'
        get 'avis', to: 'programmes#show_avis'
      end
    end
    post 'import_programmes' => 'programmes#import'

    resources :avis, only: :show
    get 'historique' => 'avis#index'
    get 'consultation' => 'avis#consultation'
    get 'remplissage_avis' => 'avis#remplissage_avis'
    get 'suivi_remplissage_avis' => 'avis#suivi_remplissage'
    get 'restitutions' => 'avis#restitutions'
    get 'restitutions_perimetre' => 'avis#restitutions_perimetre'
    post 'update_etat', to: 'avis#update_etat'
    get 'ajout_avis', to: 'avis#ajout_avis'
    post 'import_avis', to: 'avis#import'

    resources :ht2_actes do
      resources :suspensions do
        post :refus_suspension
        get :modal_delete
        get :modal_refus_suspension
      end
      collection do
        post :bulk_cloture
        get 'tableau_de_bord', to: 'ht2_actes#tableau_de_bord'
        get 'synthese_temporelle', to: 'ht2_actes#synthese_temporelle'
        get 'synthese_anomalies', to: 'ht2_actes#synthese_anomalies'
        get 'synthese_suspensions', to: 'ht2_actes#synthese_suspensions'
        get 'pdf_en_cours', to: 'ht2_actes#pdf_en_cours'
      end
      member do
        post :generate_pdf
        get :export
        get :download_attachments
      end
    end
    get 'new_modal_acte', to: 'ht2_actes#new_modal', as: 'new_modal_acte'
    get 'show_modal_acte/:id', to: 'ht2_actes#show_modal', as: 'show_modal_acte'
    get 'modal_delete_acte/:id', to: 'ht2_actes#modal_delete', as: 'modal_delete_acte'
    get 'modal_pre_instruction/:id', to: 'ht2_actes#modal_pre_instruction', as: 'modal_pre_instruction'
    get 'modal_cloture_preinstruction_acte/:id', to: 'ht2_actes#modal_cloture_preinstruction', as: 'modal_cloture_preinstruction_acte'
    get 'renvoie_instruction/:id', to: 'ht2_actes#renvoie_instruction', as: 'renvoie_instruction'
    get 'modal_renvoie_validation/:id', to: 'ht2_actes#modal_renvoie_validation', as: 'modal_renvoie_validation'
    get 'validate_acte/:id', to: 'ht2_actes#validate_acte', as: 'validate_acte'
    get 'acte_actions/:id', to: 'ht2_actes#acte_actions', as: 'acte_actions'
    post 'cloture_pre_instruction/:id', to: 'ht2_actes#cloture_pre_instruction', as: 'cloture_pre_instruction'
    get 'check_chorus_number', to: 'ht2_actes#check_chorus_number'
    get 'synthese_users_ht2_actes', to: 'ht2_actes#synthese_utilisateurs'
    get 'historique_ht2', to: 'ht2_actes#historique'
    get 'ajout_actes', to: 'ht2_actes#ajout_actes'
    post 'import_actes', to: 'ht2_actes#import'
    delete 'delete_user_actes_year', to: 'ht2_actes#delete_user_actes_year', as: 'delete_user_actes_year'

    resources :centre_financiers, only: [:new]
    post 'import_cf', to: 'centre_financiers#import'
    get '/centre_financiers/autocomplete', to: 'centre_financiers#autocomplete'

    resources :organismes, only: [:new, :index]
    post 'import_organismes', to: 'organismes#import'
    get '/organismes/autocomplete', to: 'organismes#autocomplete'

    get '/mentions-legales', to: 'pages#mentions_legales'
    get '/donnees-personnelles', to: 'pages#donnees_personnelles'
    get '/accessibilite', to: 'pages#accessibilite'
    get '/plan', to: 'pages#plan'
    get '/faq', to: 'pages#faq'
    # routes pages erreurs
    match '/500', via: :all, to: 'errors#error_500'
    match '/404', via: :all, to: 'errors#error_404'
    match '/503', via: :all, to: 'errors#error_503'
    #match '*path', to: 'errors#error_404', via: :all #commenté car sinon pb routes pour active storage loadé apres 404 et renvoie automatiquement vers 404
  end
  get '/', to: redirect('/anaco')
  # get '/500', to: redirect('/anaco/500')
  # get '/*path', to: redirect('/anaco')
end

app/models/bop.rb
class Bop < ApplicationRecord
  belongs_to :user
  belongs_to :dcb, class_name: 'User', foreign_key: 'dcb_id'
  has_many :avis, dependent: :destroy
  belongs_to :programme
  has_many :centre_financiers

  def self.import(file)

    data = Roo::Spreadsheet.open(file.path)
    headers = data.row(1) # get header row
    data.each_with_index do |row, idx|
      next if idx == 0 # skip header
      row_data = Hash[[headers, row].transpose]
      # mise à jour des dotations
      #if Bop.find_by(code: row_data['Code'])
      #  bop = Bop.find_by(code: row_data['Code'])
      #  bop.update!(dotation: row_data['Dotation'], created_at: row_data['Created at'].to_datetime)
      #end
      unless User.where(nom: row_data['Identifiant ANACO Contrôleur BOP']).first.nil?
        programme = Programme.find_by(numero: row_data['N°Programme'])
        if Bop.exists?(code: row_data['Code CHORUS du BOP'].to_s)
          @bop = Bop.where(code: row_data['Code CHORUS du BOP'].to_s).first
          @bop.update(user_id: User.where(nom: row_data['Identifiant ANACO Contrôleur BOP']).first.id, dcb_id: User.where(nom: row_data['Identifant DCB Programme ANACO'].to_s).first.id, ministere: row_data['MINISTERE'].to_s, nom_programme: row_data['Libellé programme'].to_s, numero_programme: row_data['N°Programme'].to_i, programme_id: programme.id)
        else
          bop = Bop.new(
            user_id: User.find_by(nom: row_data['Identifiant ANACO Contrôleur BOP'])&.id,
            dcb_id: User.find_by(nom: row_data['Identifant DCB Programme ANACO'].to_s)&.id,
            ministere: row_data['MINISTERE'].to_s,
            nom_programme: row_data['Libellé programme'].to_s,
            numero_programme: row_data['N°Programme'].to_i,
            programme_id: programme.id,
            code: row_data['Code CHORUS du BOP'].to_s,
            created_at: Date.current.beginning_of_year.to_datetime
          )

          # Vérifie que l'objet est valide avant de sauvegarder
          if bop.save
            puts "Bop créé avec succès : #{bop.inspect}"
          else
            puts "Erreur lors de la création du Bop : #{bop.errors.full_messages.join(', ')}"
          end
        end
      end

    end
    Bop.where(dotation: "\n").update_all(dotation: nil)
  end

  def self.ransackable_attributes(auth_object = nil)
    ["code", "dcb", "created_at", "deconcentre","dotation", "id", "id_value", "ministere", "nom_programme", "numero_programme", "updated_at", "user_id", "dcb_id", "programme_id"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["avis", "centre_financiers", "dcb", "programme", "user"]
  end
end

app/controllers/bops_controller.rb
# frozen_string_literal: true

# controller des Bop
class BopsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin!, only: [:new, :import]
  protect_from_forgery with: :null_session

  def index
    @bops = current_user.statut == 'CBR' ? current_user.bops : Bop.all
    @bops = @bops.order(code: :asc)
    @q = @bops.ransack(params[:q])
    @bops = @q.result.includes(:user)
    @pagy, @bops_page = pagy(@bops)
  end

  # page affichage du bop
  def show
    @bop = Bop.find(params[:id])
    @bop_avis = @bop.avis.where.not(phase: 'execution')
  end

  # page modification de la dotation du BOP
  def edit
    @bop = Bop.find(params[:id])
  end

  def update
    @bop = Bop.find(params[:id])
    @bop.update(dotation: params[:dotation])
    if @bop.dotation == 'aucune'
      # détruire avis sur l'année en cours (DG) si existe en brouillon
      @bop.avis.where(created_at: Date.new(@annee, 1, 1)..Date.new(@annee, 12, 31), phase: 'début de gestion')&.destroy_all
      redirect_to remplissage_avis_path, flash: { notice: 'suppression' }
    else
      redirect_to new_bop_avi_path(@bop.id)
    end
  end

  # page pour importer les BOP dans l'outil (admin)
  def new; end

  # fonction pour importer les BOP dans l'outil  (admin)
  def import
    Bop.import(params[:file])
    respond_to do |format|
      format.turbo_stream { redirect_to new_bop_path }
    end
  end
end

app/helpers/bops_helper.rb
module BopsHelper

  # fonction pour afficher la répartition des statuts des BOP par phase
  def statut_bop_repartition(avis_remplis, avis_total, annee)
    statuts_debut = statut_bop(avis_remplis, avis_total, 'début de gestion')
    statuts_crg1 = annee != @annee || @date_crg1 <= Date.today ? statut_bop(avis_remplis, avis_total, 'CRG1') : [0, 0, 0, avis_total]
    statuts_crg2 = annee != @annee || @date_crg2 <= Date.today ? statut_bop(avis_remplis, avis_total, 'CRG2') : [0, 0, 0, avis_total]
    [[statuts_debut[0], statuts_crg1[0], statuts_crg2[0]], [statuts_debut[1], statuts_crg1[1], statuts_crg2[1]],
     [statuts_debut[2], statuts_crg1[2], statuts_crg2[2]], [statuts_debut[3], statuts_crg1[3], statuts_crg2[3]]]
  end

  # fonction pour calculer les statuts des bops sur une phase
  def statut_bop(avis, avis_total, phase)
    if phase == 'CRG1'
      statuts_positive = avis.count { |a| a.phase == 'début de gestion' && a.is_crg1 == false && ((a.ae_i || 0) + (a.t2_i || 0) - (a.ae_f || 0) - (a.t2_f || 0)).positive? } + avis.count { |a| a.phase == phase && ((a.ae_i || 0) + (a.t2_i || 0) - (a.ae_f || 0) - (a.t2_f || 0)).positive? }
      statuts_nul = avis.count { |a| a.phase == 'début de gestion' && a.is_crg1 == false && ((a.ae_i || 0) + (a.t2_i || 0) - (a.ae_f || 0) - (a.t2_f || 0)).zero? } + avis.count { |a| a.phase == phase && ((a.ae_i || 0) + (a.t2_i || 0) - (a.ae_f || 0) - (a.t2_f || 0)).zero? }
      statuts_negative = avis.count { |a| a.phase == 'début de gestion' && a.is_crg1 == false && ((a.ae_i || 0) + (a.t2_i || 0) - (a.ae_f || 0) - (a.t2_f || 0)).negative? } + avis.count { |a| a.phase == phase && ((a.ae_i || 0) + (a.t2_i || 0) - (a.ae_f || 0) - (a.t2_f || 0)).negative? }
      statuts_vide = avis_total - avis.select { |a| a.phase == 'début de gestion' && a.is_crg1 == false }.count - avis.count { |a| a.phase == phase }
    else
      statuts_positive = avis.count { |a| a.phase == phase && ((a.ae_i || 0) + (a.t2_i || 0) - (a.ae_f || 0) - (a.t2_f || 0)).positive? }
      statuts_nul = avis.count { |a| a.phase == phase && ((a.ae_i || 0) + (a.t2_i || 0) - (a.ae_f || 0) - (a.t2_f || 0)).zero? }
      statuts_negative = avis.count { |a| a.phase == phase && ((a.ae_i || 0) + (a.t2_i || 0) - (a.ae_f || 0) - (a.t2_f || 0)).negative? }
      statuts_vide = avis_total - avis.count { |a| a.phase == phase }
    end
    [statuts_positive, statuts_nul, statuts_negative, statuts_vide]
  end
end

app/views/bops/_form_bop_dotation.html.erb
<div class="fr-container">
  <nav role="navigation" class="fr-breadcrumb" aria-label="vous êtes ici :">
    <button class="fr-breadcrumb__button " aria-expanded="false" aria-controls="breadcrumb-1" title="voir le fil d'ariane">Voir
      le fil d’Ariane
    </button>
    <div class="fr-collapse" id="breadcrumb-1">
      <ol class="fr-breadcrumb__list">
        <li>
          <%= link_to root_path, class: "fr-breadcrumb__link" do %> Accueil
          <% end %>
        </li>
        <li>
          <%= link_to remplissage_avis_path, class: "fr-breadcrumb__link" do %> Remplissage des avis/notes
          <% end %>
        </li>
        <li>
          <a class="fr-breadcrumb__link" aria-current="page">Dotation du bop</a>
        </li>
      </ol>
    </div>
  </nav>
  <div class="fr-grid-row fr-grid-row--gutters">
    <div class="fr-col-12 fr-col-lg-12">
      <h1>BOP n°<%= @bop.code %></h1>
    </div>
  </div>
  <div data-controller="form">
    <%= form_with(url: bop_path(@bop), method: :patch, data: { 'form-target': "form", action: "change->form#formChange" }) do |f| %>
      <div class="fr-grid-row fr-grid-row--gutters fr-mb-4w">
        <div class="fr-col-12 fr-col-lg-4">
          <div class="fr-select-group">
            <label for="dotation" class="fr-label">Dotation du BOP*
              <span class="fr-hint-text">Si le BOP est non doté, il n'y aura alors pas d'avis sur celui-ci et sera considéré comme un BOP inactif.</span></label>
            <%= f.select :dotation, [["- sélectionner -", ""], ['BOP doté en HT2 et T2', 'HT2 et T2'], ['BOP doté uniquement en HT2', 'HT2'], ['BOP doté uniquement en T2', 'T2'], ['BOP non doté', 'aucune']], { selected: @bop.dotation }, { data: { 'form-target': 'fieldRequire' }, class: "fr-select", id: "dotation" } %>
          </div>
          <div><%= f.submit "Valider et continuer", class: "fr-btn", data: { 'form-target': "Btnvalidate" }, aria: { label: "Valider et continuer" } %></div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/bops/_notice.html.erb
<% if flash.any? %>
  <% flash.each do |type, msg| %>
    <% if msg == "suppression" %>
      <div class="fr-alert fr-alert--success fr-mb-2w">
        <h3 class="fr-alert__title">Votre BOP a bien été enregistré comme BOP non doté. Il est désormais à retrouver dans la liste des BOP inactifs.</h3>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/bops/edit.html.erb
<% content_for :title do %>Formulaire BOP | ANACO <% end %>
<main role="main" class="containtAll">
  <%= render 'form_bop_dotation'%>
</main>

app/views/bops/index.html.erb
<% content_for :title do %>Liste des BOP | ANACO
<% end %>
<div class="fr-container">
  <div class="fr-grid-row fr-grid-row--gutters">
    <div class="fr-col-12 fr-col-lg-12">
      <h1 class="fr-mt-6w">Liste des BOP</h1>

      <div class="fr-table--lg fr-table fr-table--no-caption" data-controller="request">
        <%= search_form_for @q, data: { 'request-target': 'form', turbo_frame: 'table', turbo_action: 'advance' } do |f| %>
          <div class="fr-table__header">
            <div class="fr-table__detail">
              <div class="fr-search-bar" id="header-search" role="search">
                <%= f.search_field :code_contains, class: 'fr-input', placeholder: "Rechercher un BOP par son code", oninput: 'this.form.requestSubmit()' %>
                <button class="fr-btn" title="Rechercher">
                  Rechercher
                </button>
              </div>
            </div>
            <ul class="fr-btns-group fr-btns-group--right fr-btns-group--inline-md fr-btns-group--icon-left">
              <li>
                <button type="button" class="fr-btn fr-icon-filter-line fr-btn--icon-left " aria-controls="filtres" aria-expanded="false">
                  Filtrer
                </button>
              </li>
            </ul>
          </div>
          <div class="fr-collapse fr-collapse--grey fr-px-2w" id="filtres">
            <div class="fr-h4 fr-my-2w">Filtrer les résultats</div>
            <div class="fr-grid-row fr-grid-row--gutters">
              <div class="fr-col-4">
                <%= render_tag_group 'Dotation', :dotation_in, ["HT2 et T2", "HT2", "T2"] %>
              </div>
              <div class="fr-col-4">
                <%= render_select_group("Contrôleur", :user_nom_in, User.where(statut: ['DCB', 'CBR']).order(nom: :asc).map {|u| u.nom}) %>
              </div>
              <div class="fr-col-4">
                <%= render_select_group("DCB responsable", :dcb_nom_in, User.where(statut: ['DCB']).order(nom: :asc).map {|u| u.nom}) %>
              </div>
            </div>
          </div>
        <% end %>
        <%= turbo_frame_tag :table, data: { turbo_action: 'advance' } do %>
          <div class="fr-table__wrapper">
            <div class="fr-table__container">
              <div class="fr-table__content">
                <table class="fr-cell--multiline">
                  <caption>BOP</caption>
                  <thead>
                  <tr>
                    <th scope="col">BOP</th>
                    <th scope="col">Dotation</th>
                    <th scope="col">Programme</th>
                    <th scope="col">Contrôleur</th>
                    <th scope="col">DCB responsable</th>
                  </tr>
                  </thead>

                  <tbody>
                  <% @bops_page&.each do |bop| %>
                    <tr>
                      <td><%= link_to bop_path(bop.id), data: { turbo_frame: "_top" } do %><%= bop.code %>
                        <% end %></td>
                      <td>
                        <% if bop.dotation.nil? || bop.dotation.blank? %>
                          Non renseigné
                        <% elsif bop.dotation == "aucune" %>
                          inactif
                        <% else %>
                          <%= bop.dotation %>
                        <% end %>
                      </td>
                      <td><%= bop.numero_programme %> - <%= bop.nom_programme %></td>
                      <td><%= bop.user.nom %></td>
                      <td><%= bop.dcb.nom %></td>
                    </tr>
                  <% end %>
                  </tbody>

                </table>
              </div>
            </div>
          </div>
          <div class="fr-table__footer">
            <div class="fr-table__footer--start">
              <p class="fr-table__detail"><%= @bops.length %> résultats</p>
              <div class="fr-select-group">
                <label class="fr-sr-only fr-label" for="table-footer-select-7847">
                  Nombre de lignes par page
                </label>
                <div class="fr-messages-group" id="table-footer-select-7847-messages" aria-live="polite"></div>
              </div>
            </div>
            <div class="fr-table__footer--middle">
              <%== pagy_nav_custom(@pagy) %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bops/new.html.erb
<% content_for :title do %>Ajout document liste des BOP | ANACO <% end %>
<main role="main" class="containtAll">
  <div class="fr-container fr-mt-7w">
    <div class="fr-col-lg-10 fr-col-offset-lg-1">
      <h1>Ajouter un nouveau document</h1>
     <div>
      <%= form_tag import_bops_path, multipart: true do %>
        <div class="fr-upload-group">
          <label class="fr-label" for="file-upload">Ajouter des fichiers
              <span class="fr-hint-text">Taille maximale : 500 Mo. Formats supportés : xlsx. </span>
          </label>
          <%= file_field_tag  :file, accept: '.xlsx', class: "fr-upload", id: "file-upload" %>
        </div>
        <div class="fr-my-4w"><%= submit_tag "Transmettre", class:"fr-btn" %></div>
        <% end %>
    </div>
    <div class="fr-my-4w"><%= Bop.all.count%> bops</div>
      <% User.all.order(nom: :asc).each do |user| %>
        <div><%= user.nom %> - <%= user.bops.count %></div>
      <%end %>
    </div>
</div>
</main>

app/views/bops/show.html.erb
<% content_for :title do %>Informations du BOP n°<%= @bop.code %> | ANACO
<% end %>
<main role="main" class="containtAll">
  <div class="fr-container">
    <nav role="navigation" class="fr-breadcrumb" aria-label="vous êtes ici :">
      <button class="fr-breadcrumb__button " aria-expanded="false" aria-controls="breadcrumb-1" title="voir le fil d'ariane">
        Voir le fil d’Ariane
      </button>
      <div class="fr-collapse" id="breadcrumb-1">
        <ol class="fr-breadcrumb__list">
          <li>
            <%= link_to root_path, class: "fr-breadcrumb__link" do %> Accueil
            <% end %>
          </li>
          <li>
            <%= link_to bops_path, class: "fr-breadcrumb__link" do %> Liste des BOP
            <% end %>
          </li>
          <li>
            <a class="fr-breadcrumb__link" aria-current="page">BOP n°<%= @bop.code %></a>
          </li>
        </ol>
      </div>
    </nav>
    <div class="fr-grid-row fr-grid-row--gutters">
      <div class="fr-col-12 fr-col-lg-12">
        <h1 class="fr-mb-3w">BOP n°<%= @bop.code %></h1>
      </div>
    </div>

    <div class="fr-card fr-card--horizontal fr-card--shadow fr-mb-4w">
      <div class="fr-card__body">
        <div class="fr-card__content">
          <div class="fr-card__start">
            <ul class="fr-badges-group">
              <li>
                <p class="fr-tag"> Ministere <%= @bop.ministere %></p>
              </li>
            </ul>
            <p class="fr-card__detail fr-icon-arrow-right-line">DCB responsable : <%= @bop.dcb.nom %></p>
          </div>
          <h3 class="fr-card__title">BOP n°<%= @bop.code %></h3>
          <div class="fr-card__desc">
            <p class="fr-mb-1w"><%= link_to programme_path(@bop.programme) do %>Programme n°<%= @bop.numero_programme %>
                - <%= @bop.nom_programme %>
              <% end %></p>
            <p>Contrôleur : <%= @bop.user.nom %></p>
            <div><p class="fr-badge fr-badge--sm fr-badge--blue-ecume">
              <% if @bop.dotation == "aucune" %>BOP inactif
              <% elsif @bop.dotation.nil? || @bop.dotation.blank? %>Dotation non renseignée
              <% else %>BOP doté en <%= @bop.dotation %>
              <% end %></p>
            </div>
          </div>
        </div>
      </div>
    </div>


    <div class="fr-grid-row fr-grid-row--gutters fr-mb-6w">
      <div class="fr-col-12 fr-col-lg-12">
        <h2 class="fr-mb-3w">Historique des avis</h2>
        <%= render 'avis/success' %>
        <div class="fr-tabs">
          <ul class="fr-tabs__list" role="tablist" aria-label="Avis du bop par année">
            <% (Date.today.year).downto(2023).to_a.each do |annee| %>
              <li role="presentation">
                <button id="tabpanel-<%= annee %>" class="fr-tabs__tab" tabindex="<%= annee == Date.today.year ? '0' : '-1' %>" role="tab" aria-selected="<%= annee == Date.today.year ? 'true' : 'false' %>" aria-controls="tabpanel-<%= annee %>-panel"><%= annee %></button>
              </li>
            <% end %>
          </ul>
          <% (Date.today.year).downto(2023).to_a.each do |annee| %>
            <div id="tabpanel-<%= annee %>-panel" class="fr-tabs__panel <%= annee == Date.today.year ? 'fr-tabs__panel--selected' : '' %>" role="tabpanel" aria-labelledby="tabpanel-<%= annee %>" tabindex="0">
              <% liste_avis_annee = @bop_avis.order(created_at: :desc).select { |avis| avis.annee == annee } %>
              <% if liste_avis_annee.empty? %>
                <p>Aucun avis</p>
              <% else %>
                <div class="fr-table--lg fr-table fr-table--no-caption">
                  <div class="fr-table__wrapper">
                    <div class="fr-table__container">
                      <div class="fr-table__content">
                        <table>
                          <caption>Historique des avis</caption>
                          <thead>
                          <tr>
                            <th scope="col">Date de création</th>
                            <th scope="col">Phase</th>
                            <th scope="col">Statut</th>
                            <th scope="col">État</th>
                            <th scope="col">Action</th>

                          </tr>
                          </thead>
                          <tbody>
                          <% liste_avis_annee.each do |avis| %>
                            <tr>
                              <td><%= l(avis.created_at, format: "%e/%m/%y") %></td>
                              <td>
                                <div class="fr-capitalize"><%= avis.phase %></div>
                                <% if avis.phase == 'services votés' %>
                                  n°<%= numero_avis_services_votes(avis, liste_avis_annee) %>
                                <% end %>
                              </td>
                              <td><%= avis.statut %></td>
                              <td>
                                <p class="<%= badge_class_for_etat(avis.etat) %>"><%= avis.etat %></p>
                              </td>
                              <td>
                                <% if avis.etat == "Brouillon" && avis.user == current_user %>
                                  <%= link_to edit_bop_avi_path(bop_id: @bop.id, id: avis.id), class: "fr-btn" do %>
                                    Reprendre
                                  <% end %>
                                <% elsif avis.etat != "Brouillon" %>
                                  <a href="<%= avi_path(avis) %>" data-turbo-frame="modal" class="fr-btn" data-fr-opened="false" aria-controls="modal-1">
                                    Consulter
                                  </a>

                                  <% if current_user == avis.user %>
                                    <%= link_to edit_bop_avi_path(bop_id: @bop.id, id: avis.id), class: "fr-btn fr-btn--secondary" do %>
                                      Modifier
                                    <% end %>
                                  <% end %>
                                <% end %>
                              </td>

                            </tr>
                          <% end %>
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <dialog id="modal-1" class="fr-modal">
      <%= turbo_frame_tag :modal, target: "_top" %>
    </dialog>

  </div>
</main>