config/routes.rb
Rails.application.routes.draw do
  get "suspensions/edit"
  get "suspensions/update"
  get "suspensions/destroy"
  scope(:path => '/anaco') do
    # 1. Routes Active Storage (montées manuellement ici) #Attention enlever match 404 si on eleve ces routes
    #scope '/rails/active_storage' do
    #  get '/blobs/redirect/:signed_id/*filename', to: 'active_storage/blobs/redirect#show', as: :rails_service_blob
    #  get '/blobs/proxy/:signed_id/*filename', to: 'active_storage/blobs/proxy#show', as: :rails_service_blob_proxy
    #  get '/blobs/:signed_id/*filename', to: 'active_storage/blobs/redirect#show'
    #  get '/representations/redirect/:signed_blob_id/:variation_key/*filename', to: 'active_storage/representations/redirect#show', as: :rails_blob_representation
    #  get '/representations/proxy/:signed_blob_id/:variation_key/*filename', to: 'active_storage/representations/proxy#show', as: :rails_blob_representation_proxy
    #  get '/representations/:signed_blob_id/:variation_key/*filename', to: 'active_storage/representations/redirect#show'
    #  get '/disk/:encoded_key/*filename', to: 'active_storage/disk#show', as: :rails_disk_service
    #  put '/disk/:encoded_token', to: 'active_storage/disk#update', as: :update_rails_disk_service
    #  post '/direct_uploads', to: 'active_storage/direct_uploads#create', as: :rails_direct_uploads
    #end

    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)
    devise_for :users, path: '',
               path_names: { sign_in: 'connexion', sign_out: 'logout' },
               controllers: { sessions: 'sessions' }

    root 'pages#index'
    get 'global_search', to: 'pages#global_search'
    get 'utilisateurs' => 'users#index'
    post 'import_users' => 'users#import'
    post '/select_nom' => 'users#select_nom'

    get 'suivi_remplissage_schemas', to: 'users#suivi_remplissage_schemas'

    resources :bops do
      resources :avis, only: [:new, :create, :edit, :update]
    end
    post 'import_bops' => 'bops#import'
    post 'filter_bop', to: 'bops#filter_bop'

    resources :missions
    resources :ministeres

    # resources :gestion_schemas, except: [:new, :create]
    resources :schemas, except: [:new, :create] do
      resources :gestion_schemas
      member do
        get 'confirm_delete' => "schemas#confirm_delete"
        get 'pdf_vision' => "schemas#pdf_vision"
      end
    end
    get 'schemas_remplissage' => "schemas#schemas_remplissage"
    get 'generate_schemas_pdf' => "schemas#generate_schemas_pdf"

    resources :programmes do
      resources :schemas, only: [:new, :create]
      member do
        get 'last_schema', to: 'programmes#show_last_schema'
        get 'avis', to: 'programmes#show_avis'
      end
    end
    post 'import_programmes' => 'programmes#import'

    resources :avis, only: :show
    get 'historique' => 'avis#index'
    get 'consultation' => 'avis#consultation'
    get 'remplissage_avis' => 'avis#remplissage_avis'
    get 'suivi_remplissage_avis' => 'avis#suivi_remplissage'
    get 'restitutions' => 'avis#restitutions'
    get 'restitutions_perimetre' => 'avis#restitutions_perimetre'
    post 'update_etat', to: 'avis#update_etat'
    get 'ajout_avis', to: 'avis#ajout_avis'
    post 'import_avis', to: 'avis#import'

    resources :ht2_actes do
      resources :suspensions do
        post :refus_suspension
        get :modal_delete
        get :modal_refus_suspension
      end
      collection do
        post :bulk_cloture
        get 'tableau_de_bord', to: 'ht2_actes#tableau_de_bord'
        get 'synthese_temporelle', to: 'ht2_actes#synthese_temporelle'
        get 'synthese_anomalies', to: 'ht2_actes#synthese_anomalies'
        get 'synthese_suspensions', to: 'ht2_actes#synthese_suspensions'
        get 'pdf_en_cours', to: 'ht2_actes#pdf_en_cours'
      end
      member do
        post :generate_pdf
        get :export
        get :download_attachments
      end
    end
    get 'new_modal_acte', to: 'ht2_actes#new_modal', as: 'new_modal_acte'
    get 'show_modal_acte/:id', to: 'ht2_actes#show_modal', as: 'show_modal_acte'
    get 'modal_delete_acte/:id', to: 'ht2_actes#modal_delete', as: 'modal_delete_acte'
    get 'modal_pre_instruction/:id', to: 'ht2_actes#modal_pre_instruction', as: 'modal_pre_instruction'
    get 'modal_cloture_preinstruction_acte/:id', to: 'ht2_actes#modal_cloture_preinstruction', as: 'modal_cloture_preinstruction_acte'
    get 'renvoie_instruction/:id', to: 'ht2_actes#renvoie_instruction', as: 'renvoie_instruction'
    get 'modal_renvoie_validation/:id', to: 'ht2_actes#modal_renvoie_validation', as: 'modal_renvoie_validation'
    get 'validate_acte/:id', to: 'ht2_actes#validate_acte', as: 'validate_acte'
    get 'acte_actions/:id', to: 'ht2_actes#acte_actions', as: 'acte_actions'
    post 'cloture_pre_instruction/:id', to: 'ht2_actes#cloture_pre_instruction', as: 'cloture_pre_instruction'
    get 'check_chorus_number', to: 'ht2_actes#check_chorus_number'
    get 'synthese_users_ht2_actes', to: 'ht2_actes#synthese_utilisateurs'
    get 'historique_ht2', to: 'ht2_actes#historique'
    get 'ajout_actes', to: 'ht2_actes#ajout_actes'
    post 'import_actes', to: 'ht2_actes#import'
    delete 'delete_user_actes_year', to: 'ht2_actes#delete_user_actes_year', as: 'delete_user_actes_year'

    resources :centre_financiers, only: [:new]
    post 'import_cf', to: 'centre_financiers#import'
    get '/centre_financiers/autocomplete', to: 'centre_financiers#autocomplete'

    resources :organismes, only: [:new, :index]
    post 'import_organismes', to: 'organismes#import'
    get '/organismes/autocomplete', to: 'organismes#autocomplete'

    get '/mentions-legales', to: 'pages#mentions_legales'
    get '/donnees-personnelles', to: 'pages#donnees_personnelles'
    get '/accessibilite', to: 'pages#accessibilite'
    get '/plan', to: 'pages#plan'
    get '/faq', to: 'pages#faq'
    # routes pages erreurs
    match '/500', via: :all, to: 'errors#error_500'
    match '/404', via: :all, to: 'errors#error_404'
    match '/503', via: :all, to: 'errors#error_503'
    #match '*path', to: 'errors#error_404', via: :all #commenté car sinon pb routes pour active storage loadé apres 404 et renvoie automatiquement vers 404
  end
  get '/', to: redirect('/anaco')
  # get '/500', to: redirect('/anaco/500')
  # get '/*path', to: redirect('/anaco')
end

app/models/mission.rb
class Mission < ApplicationRecord
  has_many :programmes

  def total_ae_rprog_ht2_for_mission(annee)
    self.programmes.sum { |programme| programme.last_schema_valid(annee)&.gestion_schemas&.rprog_ht2&.first&.solde_total_ae || 0 }
  end
  def total_cp_rprog_ht2_for_mission(annee)
    self.programmes.sum { |programme| programme.last_schema_valid(annee)&.gestion_schemas&.rprog_ht2&.first&.solde_total_cp || 0 }
  end
  def total_ae_rprog_t2_for_mission(annee)
    self.programmes.sum { |programme| programme.last_schema_valid(annee)&.gestion_schemas&.rprog_t2&.first&.solde_total_ae || 0 }
  end
  def total_cp_rprog_t2_for_mission(annee)
    self.programmes.sum { |programme| programme.last_schema_valid(annee)&.gestion_schemas&.rprog_t2&.first&.solde_total_cp || 0 }
  end
  def total_ae_cbcm_ht2_for_mission(annee)
    self.programmes.sum { |programme| programme.last_schema_valid(annee)&.gestion_schemas&.cbcm_ht2&.first&.solde_total_ae || 0 }
  end
  def total_cp_cbcm_ht2_for_mission(annee)
    self.programmes.sum { |programme| programme.last_schema_valid(annee)&.gestion_schemas&.cbcm_ht2&.first&.solde_total_cp || 0 }
  end
  def total_ae_cbcm_t2_for_mission(annee)
    self.programmes.sum { |programme| programme.last_schema_valid(annee)&.gestion_schemas&.cbcm_t2&.first&.solde_total_ae || 0 }
  end
  def total_cp_cbcm_t2_for_mission(annee)
    self.programmes.sum { |programme| programme.last_schema_valid(annee)&.gestion_schemas&.cbcm_t2&.first&.solde_total_cp || 0 }
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "id_value", "nom", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["programmes"]
  end

  ransacker :nom, type: :string do
    Arel.sql("unaccent(missions.\"nom\")")
  end
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  before_action :authenticate_user!
  include ApplicationHelper
  def index
    @missions = Mission.all.order(nom: :asc)
  end

  def show
    @mission = Mission.find(params[:id])
    @annee_a_afficher = annee_a_afficher
    @programmes = @mission.programmes.includes(schemas: :gestion_schemas).where(statut: 'Actif').order(numero: :asc)
    filename = "schemas_mission.xlsx"
    respond_to do |format|
      format.html
      format.xlsx { headers['Content-Disposition'] = "attachment; filename=\"#{filename}\"" }
    end
  end
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/views/missions/index.html.erb
<% content_for :title do %>Restitutions par missions | ANACO <% end %>
<main>
  <div class="fr-container">
    <h1 class="fr-mt-6w">Missions [<%= @missions&.length %>]</h1>
    <div class="fr-grid-row fr-grid-row--gutters">
      <% @missions&.each do |mission| %>
        <div class="fr-col-12 fr-col-lg-3">
          <div class="fr-card">
            <div class="fr-card__body">
              <div class="fr-card__content">
                <div class="fr-card__start">
                  <ul class="fr-badges-group">
                    <li>
                      <p class="fr-badge fr-badge--purple-glycine">schema fin de gestion </p>
                    </li>
                  </ul>
                  <p class="fr-card__detail fr-icon-arrow-right-line"><%= mission.programmes&.length %> programmes</p>
                </div>
                <h3 class="fr-card__title"><%= mission.nom %> </h3>

              </div>
              <div class="fr-card__footer">
                <ul class="fr-links-group">
                  <li>
                    <%= link_to mission_path(mission), class: "fr-link fr-icon-arrow-right-line fr-link--icon-right" do %> Afficher <% end %>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      <%end  %>
    </div>
  </div>
</main>

app/views/missions/show.html.erb
<% content_for :title do %>Mission <%= @mission.nom %> | ANACO
<% end %>
<main>
  <div class="fr-container">
    <h1 class="fr-mt-6w">Mission <%= @mission.nom %></h1>
    <div class="fr-mb-2w">
      <ul class="fr-tags-group">
        <% (2024..Date.today.year).to_a.each do |annee| %>
          <li>
            <%= link_to mission_path(@mission, date: annee), class: "fr-tag", 'aria-pressed' => (@annee_a_afficher == annee ? 'true' : 'false') do %>
              <%= annee %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="fr-alert fr-alert--warning fr-mb-2w">
      <h3 class="fr-alert__title">La vision mission peut présenter des données incomplètes car il est possible que
        certains programmes ne soient pas renseignés dans ANACO.</h3>
    </div>

    <h2>Cumul des soldes des programmes de la mission</h2>
    <div class="fr-table fr-table--bordered fr-table--no-caption ">
      <div class="fr-table__wrapper">
        <div class="fr-table__container">
          <div class="fr-table__content">
            <table>
              <caption>
                Détail des données budgétaires par programme
              </caption>
              <thead>
              <tr>
                <th class="fr-cell--fixed" role="columnheader" rowspan="3">
                  <span class="fr-sr-only">Données</span>
                </th>
                <th colspan="4">
                  HT2
                </th>
                <th colspan="4">
                  T2
                </th>
              </tr>
              <tr>
                <th colspan="2">
                  Vision RPROG
                </th>
                <th colspan="2">
                  Vision CBCM
                </th>
                <th colspan="2">
                  Vision RPROG
                </th>
                <th colspan="2">
                  Vision CBCM
                </th>
              </tr>
              <tr>
                <th scope="col">
                  AE (€)
                </th>
                <th scope="col">
                  CP (€)
                </th>
                <th scope="col">
                  AE (€)
                </th>
                <th scope="col">
                  CP (€)
                </th>
                <th scope="col">
                  HCAS (€)
                </th>
                <th scope="col">
                  CAS (€)
                </th>
                <th scope="col">
                  HCAS (€)
                </th>
                <th scope="col">
                  CAS (€)
                </th>
              </tr>
              </thead>
              <tbody>
              <% @programmes.each do |programme| %>
                <% schema = programme.last_schema_valid(@annee_a_afficher) %>
                <tr>
                  <th class="fr-cell--fixed" scope="row">P <%= programme.numero %></th>
                  <td class="fr-cell--right"><%= format_number(schema&.gestion_schemas&.rprog_ht2&.first&.solde_total_ae) %></td>
                  <td class="fr-cell--right"><%= format_number(schema&.gestion_schemas&.rprog_ht2&.first&.solde_total_cp) %></td>
                  <td class="fr-cell--right"><%= format_number(schema&.gestion_schemas&.cbcm_ht2&.first&.solde_total_ae) %></td>
                  <td class="fr-cell--right"><%= format_number(schema&.gestion_schemas&.cbcm_ht2&.first&.solde_total_cp) %></td>
                  <td class="fr-cell--right"><%= format_number(schema&.gestion_schemas&.rprog_t2&.first&.solde_total_ae) %></td>
                  <td class="fr-cell--right"><%= format_number(schema&.gestion_schemas&.rprog_t2&.first&.solde_total_cp) %></td>
                  <td class="fr-cell--right"><%= format_number(schema&.gestion_schemas&.cbcm_t2&.first&.solde_total_ae) %></td>
                  <td class="fr-cell--right"><%= format_number(schema&.gestion_schemas&.cbcm_t2&.first&.solde_total_cp) %></td>
                </tr>
              <% end %>
              <tr class="fr-table--total">
                <th class="fr-cell--fixed" scope="row">Total</th>
                <td class="fr-cell--right"><%= format_number(@mission.total_ae_rprog_ht2_for_mission(@annee_a_afficher)) %></td>
                <td class="fr-cell--right"><%= format_number(@mission.total_cp_rprog_ht2_for_mission(@annee_a_afficher)) %></td>
                <td class="fr-cell--right"><%= format_number(@mission.total_ae_cbcm_ht2_for_mission(@annee_a_afficher)) %></td>
                <td class="fr-cell--right"><%= format_number(@mission.total_cp_cbcm_ht2_for_mission(@annee_a_afficher)) %></td>
                <td class="fr-cell--right"><%= format_number(@mission.total_ae_rprog_t2_for_mission(@annee_a_afficher)) %></td>
                <td class="fr-cell--right"><%= format_number(@mission.total_cp_rprog_t2_for_mission(@annee_a_afficher)) %></td>
                <td class="fr-cell--right"><%= format_number(@mission.total_ae_cbcm_t2_for_mission(@annee_a_afficher)) %></td>
                <td class="fr-cell--right"><%= format_number(@mission.total_cp_cbcm_t2_for_mission(@annee_a_afficher)) %></td>
              </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    <div class="fr-download">
      <p><%= link_to mission_path(@mission,date: @annee_a_afficher, format: :xlsx), class: "fr-download__link" do %> Télécharger le cumul et le détail des schémas de fin de gestion <%= @annee_a_afficher %> des programmes
          <span class="fr-download__detail">Format .xlsx</span>
        <%end %></p>
    </div>
    <h2>Détails des schémas de fin de gestion <%= @annee_a_afficher %> des programmes de la mission</h2>
    <div class="fr-accordions-group fr-mb-4w">
      <% @programmes.each_with_index do |programme, index| %>
        <section class="fr-accordion">
          <h3 class="fr-accordion__title">
            <button class="fr-accordion__btn" aria-expanded="false" aria-controls="accordion-<%= index %>">Programme <%= programme.numero %></button>
          </h3>
          <div class="fr-collapse" id="accordion-<%= index %>">
            <%= turbo_frame_tag :show, src: last_schema_programme_path(programme, date: @annee_a_afficher) %>
          </div>
        </section>
      <% end %>
    </div>
  </div>
</main>