config/routes.rb
Rails.application.routes.draw do
  get "suspensions/edit"
  get "suspensions/update"
  get "suspensions/destroy"
  scope(:path => '/anaco') do
    # 1. Routes Active Storage (montées manuellement ici) #Attention enlever match 404 si on eleve ces routes
    #scope '/rails/active_storage' do
    #  get '/blobs/redirect/:signed_id/*filename', to: 'active_storage/blobs/redirect#show', as: :rails_service_blob
    #  get '/blobs/proxy/:signed_id/*filename', to: 'active_storage/blobs/proxy#show', as: :rails_service_blob_proxy
    #  get '/blobs/:signed_id/*filename', to: 'active_storage/blobs/redirect#show'
    #  get '/representations/redirect/:signed_blob_id/:variation_key/*filename', to: 'active_storage/representations/redirect#show', as: :rails_blob_representation
    #  get '/representations/proxy/:signed_blob_id/:variation_key/*filename', to: 'active_storage/representations/proxy#show', as: :rails_blob_representation_proxy
    #  get '/representations/:signed_blob_id/:variation_key/*filename', to: 'active_storage/representations/redirect#show'
    #  get '/disk/:encoded_key/*filename', to: 'active_storage/disk#show', as: :rails_disk_service
    #  put '/disk/:encoded_token', to: 'active_storage/disk#update', as: :update_rails_disk_service
    #  post '/direct_uploads', to: 'active_storage/direct_uploads#create', as: :rails_direct_uploads
    #end

    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)
    devise_for :users, path: '',
               path_names: { sign_in: 'connexion', sign_out: 'logout' },
               controllers: { sessions: 'sessions' }

    root 'pages#index'
    get 'global_search', to: 'pages#global_search'
    get 'utilisateurs' => 'users#index'
    post 'import_users' => 'users#import'
    post '/select_nom' => 'users#select_nom'

    get 'suivi_remplissage_schemas', to: 'users#suivi_remplissage_schemas'

    resources :bops do
      resources :avis, only: [:new, :create, :edit, :update]
    end
    post 'import_bops' => 'bops#import'
    post 'filter_bop', to: 'bops#filter_bop'

    resources :missions
    resources :ministeres

    # resources :gestion_schemas, except: [:new, :create]
    resources :schemas, except: [:new, :create] do
      resources :gestion_schemas
      member do
        get 'confirm_delete' => "schemas#confirm_delete"
        get 'pdf_vision' => "schemas#pdf_vision"
      end
    end
    get 'schemas_remplissage' => "schemas#schemas_remplissage"
    get 'generate_schemas_pdf' => "schemas#generate_schemas_pdf"

    resources :programmes do
      resources :schemas, only: [:new, :create]
      member do
        get 'last_schema', to: 'programmes#show_last_schema'
        get 'avis', to: 'programmes#show_avis'
      end
    end
    post 'import_programmes' => 'programmes#import'

    resources :avis, only: :show
    get 'historique' => 'avis#index'
    get 'consultation' => 'avis#consultation'
    get 'remplissage_avis' => 'avis#remplissage_avis'
    get 'suivi_remplissage_avis' => 'avis#suivi_remplissage'
    get 'restitutions' => 'avis#restitutions'
    get 'restitutions_perimetre' => 'avis#restitutions_perimetre'
    post 'update_etat', to: 'avis#update_etat'
    get 'ajout_avis', to: 'avis#ajout_avis'
    post 'import_avis', to: 'avis#import'

    resources :ht2_actes do
      resources :suspensions do
        post :refus_suspension
        get :modal_delete
        get :modal_refus_suspension
      end
      collection do
        post :bulk_cloture
        get 'tableau_de_bord', to: 'ht2_actes#tableau_de_bord'
        get 'synthese_temporelle', to: 'ht2_actes#synthese_temporelle'
        get 'synthese_anomalies', to: 'ht2_actes#synthese_anomalies'
        get 'synthese_suspensions', to: 'ht2_actes#synthese_suspensions'
        get 'pdf_en_cours', to: 'ht2_actes#pdf_en_cours'
      end
      member do
        post :generate_pdf
        get :export
        get :download_attachments
      end
    end
    get 'new_modal_acte', to: 'ht2_actes#new_modal', as: 'new_modal_acte'
    get 'show_modal_acte/:id', to: 'ht2_actes#show_modal', as: 'show_modal_acte'
    get 'modal_delete_acte/:id', to: 'ht2_actes#modal_delete', as: 'modal_delete_acte'
    get 'modal_pre_instruction/:id', to: 'ht2_actes#modal_pre_instruction', as: 'modal_pre_instruction'
    get 'modal_cloture_preinstruction_acte/:id', to: 'ht2_actes#modal_cloture_preinstruction', as: 'modal_cloture_preinstruction_acte'
    get 'renvoie_instruction/:id', to: 'ht2_actes#renvoie_instruction', as: 'renvoie_instruction'
    get 'modal_renvoie_validation/:id', to: 'ht2_actes#modal_renvoie_validation', as: 'modal_renvoie_validation'
    get 'validate_acte/:id', to: 'ht2_actes#validate_acte', as: 'validate_acte'
    get 'acte_actions/:id', to: 'ht2_actes#acte_actions', as: 'acte_actions'
    post 'cloture_pre_instruction/:id', to: 'ht2_actes#cloture_pre_instruction', as: 'cloture_pre_instruction'
    get 'check_chorus_number', to: 'ht2_actes#check_chorus_number'
    get 'synthese_users_ht2_actes', to: 'ht2_actes#synthese_utilisateurs'
    get 'historique_ht2', to: 'ht2_actes#historique'
    get 'ajout_actes', to: 'ht2_actes#ajout_actes'
    post 'import_actes', to: 'ht2_actes#import'
    delete 'delete_user_actes_year', to: 'ht2_actes#delete_user_actes_year', as: 'delete_user_actes_year'

    resources :centre_financiers, only: [:new]
    post 'import_cf', to: 'centre_financiers#import'
    get '/centre_financiers/autocomplete', to: 'centre_financiers#autocomplete'

    resources :organismes, only: [:new, :index]
    post 'import_organismes', to: 'organismes#import'
    get '/organismes/autocomplete', to: 'organismes#autocomplete'

    get '/mentions-legales', to: 'pages#mentions_legales'
    get '/donnees-personnelles', to: 'pages#donnees_personnelles'
    get '/accessibilite', to: 'pages#accessibilite'
    get '/plan', to: 'pages#plan'
    get '/faq', to: 'pages#faq'
    # routes pages erreurs
    match '/500', via: :all, to: 'errors#error_500'
    match '/404', via: :all, to: 'errors#error_404'
    match '/503', via: :all, to: 'errors#error_503'
    #match '*path', to: 'errors#error_404', via: :all #commenté car sinon pb routes pour active storage loadé apres 404 et renvoie automatiquement vers 404
  end
  get '/', to: redirect('/anaco')
  # get '/500', to: redirect('/anaco/500')
  # get '/*path', to: redirect('/anaco')
end

app/models/schema.rb
class Schema < ApplicationRecord
  belongs_to :programme
  belongs_to :user
  has_many :gestion_schemas, dependent: :destroy
  has_one_attached :document_pdf

  def incomplete?
    !self.gestion_schemas.empty? && self.statut != 'valide'
  end

  def complete?
    self.statut == 'valide'
  end

  def gestion_schemas_empty?
    self.gestion_schemas.empty?
  end

  def first_of_year?
    self.programme.schemas.where(annee: Date.today_year).count == 1
  end

  def last_gestion_schema
    self.gestion_schemas.order(created_at: :desc).first
  end

  def self.ransackable_associations(auth_object = nil)
    ["gestion_schemas", "programme", "user"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["annee", "created_at", "id", "id_value", "programme_id", "statut", "updated_at", "user_id", "document_pdf_attachment_id_eq", "document_pdf_blob_id_eq"]
  end

end

app/controllers/schemas_controller.rb
class SchemasController < ApplicationController
  before_action :authenticate_user!, except: [:pdf_vision]
  before_action :authenticate_dcb_or_admin!, except: [:pdf_vision, :show]
  before_action :authenticate_admin!, only: [:generate_schemas_pdf]
  before_action :set_schema, only: [:destroy, :show, :confirm_delete, :pdf_vision]
  before_action :set_programme, only: [:create]
  before_action :retrieve_last_schema_and_redirect_if_incomplete, only: [:create]
  include ApplicationHelper
  include GestionSchemasHelper

  def index
    # récupérer la liste des schémas triés par ordre croissant
    @schemas = current_user.statut == 'DCB' ? current_user.schemas.joins(:gestion_schemas).distinct : Schema.where(statut: 'valide')
    @schemas = @schemas.order(updated_at: :desc)
    # recherche filtres ransack
    @q = @schemas.ransack(params[:q])
    @schemas = @q.result.includes(:programme, :user, gestion_schemas: :transferts)
    # paginger les résultats
    @pagy, @schemas_page = pagy(@schemas)
  end

  def create
    # démarrer direct à l'étape 3 si doté uniquement en T2
    @statut = @programme.dotation == 'T2' ? '3' : '1'
    @schema = @programme.schemas.create(user_id: @programme.user_id, annee: Date.today.year, statut: @statut)

    redirect_to new_schema_gestion_schema_path(@schema)
  end

  # suivi remplissage des schémas par programme pour les DCB
  def schemas_remplissage
    @programmes = current_user.programmes.active.order(numero: :asc)
    @annee_a_afficher = annee_a_afficher
  end

  def show
    @gestion_schemas = @schema.gestion_schemas.includes(transferts: :programme)
    @vision_rprog_ht2 = @schema.gestion_schemas.find_by(vision: 'RPROG', profil: 'HT2')
    @vision_rprog_t2 = @schema.gestion_schemas.find_by(vision: 'RPROG', profil: 'T2')
    @vision_cbcm_ht2 = @schema.gestion_schemas.find_by(vision: 'CBCM', profil: 'HT2')
    @vision_cbcm_t2 = @schema.gestion_schemas.find_by(vision: 'CBCM', profil: 'T2')
    filename = "Schema_fin_de_gestion_P#{@schema.programme.numero}.xlsx"
    respond_to do |format|
      format.html
      format.xlsx { headers['Content-Disposition'] = "attachment; filename=\"#{filename}\"" }
    end
  end

  def destroy
    @schema&.destroy
    redirect_to schemas_path
  end

  def confirm_delete; end

  def pdf_vision
    @gestion_schemas = @schema.gestion_schemas.includes(transferts: :programme)

    respond_to do |format|
      format.html
      format.pdf do
        if @schema.document_pdf.attached? # vérifiez si un pdf est attaché
          send_data(
            @schema.document_pdf.download, # envoyez le pdf attaché
            filename: @schema.document_pdf.filename.to_s,
            type: "application/pdf",
            disposition: "attachment"
          )
        else
          url = pdf_vision_schema_url(@schema)
          tmp_path = UrlToPdfJob.perform_now(url)
          # envoyer le pdf en réponse
          pdf_data = File.read(tmp_path)
          send_data(pdf_data,
                    filename: "schema_P#{@schema.programme.numero}.pdf",
                    type: "application/pdf",
                    disposition: "attachment") # inline open in browser
          # disposition: "attachment") # default # download
          # ouvrir le fichier temporaire et attacher au modèle Schema
          File.open(tmp_path) do |file|
            @schema.document_pdf.attach(io: file, filename: "schema_P#{@schema.programme.numero}.pdf")
          end

          # assurez-vous de supprimer le fichier temporaire après son utilisation
          File.delete(tmp_path)
        end
      end
    end
  end

  def generate_schemas_pdf; end

  private

  def set_schema
    @schema = Schema.includes(:programme).find(params[:id])
  end

  def set_programme
    @programme = Programme.find(params[:programme_id])
  end

  def retrieve_last_schema_and_redirect_if_incomplete
    last_schema = @programme.last_schema(@annee)
    redirect_to new_schema_gestion_schema_path(@schema) and return if last_schema&.incomplete?
  end
end

app/helpers/schemas_helper.rb
module SchemasHelper

  def numero_version(schema)
    schemas = Schema.where(programme_id: schema.programme_id, annee: schema.annee).order(:created_at)
    schemas.index(schema) + 1
  end
end

app/views/schemas/confirm_delete.html.erb
<%= turbo_frame_tag :modal, target: "_top" do %>
  <% if @schema %>
      <div class="fr-container fr-container--fluid fr-container-md">
        <div class="fr-grid-row fr-grid-row--center">
          <div class="fr-col-12 fr-col-md-8 fr-col-lg-6">
            <div class="fr-modal__body">
              <div class="fr-modal__header">
                <button class="fr-btn--close fr-btn" aria-controls="fr-modal-2">Fermer</button>
              </div>
              <div class="fr-modal__content">
                <h1 id="fr-modal-2-title" class="fr-modal__title">
                  <span class="fr-icon-arrow-right-line fr-icon--lg"></span>
                  Supprimer la proposition de contribution au schéma de fin de gestion
                </h1>
                <div class="fr-alert fr-alert--warning fr-mb-2w">
                  <h3 class="fr-alert__title">Vous êtes sur le point de supprimer la version n°<%= numero_version(@schema) %> du
                    programme <%= @schema.programme.numero %></h3>
                </div>
                <p>Attention, si vous validez, la contribution sera supprimée définitivement. Cliquer sur annuler pour
                  revenir en arrière.</p>
              </div>
              <div class="fr-modal__footer">
                <div class="fr-btns-group fr-btns-group--right fr-btns-group--inline-reverse fr-btns-group--inline-lg fr-btns-group--icon-left">
                  <button class="fr-btn">
                    <%= link_to schema_path(@schema), data: { "turbo_method": :delete } do %>Confirmer la suppression
                    <% end %>
                  </button>
                  <button class="fr-btn fr-btn--secondary" aria-controls="fr-modal-2">
                    Annuler
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

  <% end %>
<% end %>

app/views/schemas/generate_schemas_pdf.html.erb
<div class="fr-container">
  <div class="fr-grid-row fr-grid-row--gutters">
    <div class="fr-col-12 fr-col-lg-12">
      <% Schema.where(statut: 'valide').each do |schema| %>
        <% if !schema.document_pdf.attached? %>
          <div>Schema <%= schema.id %> - <%= schema.user.nom %> - <%= schema.annee %> - <%= link_to programme_path(schema.programme) do %><%= schema.programme.numero %><% end %>
          <%= link_to pdf_vision_schema_path(schema, format: :pdf), target: :_blank, class: "fr-link fr-link--download" do %>
            Générer le schéma au format PDF <span class="fr-link__detail">Format .pdf</span>
          <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/schemas/index.html.erb
<% content_for :title do %>Historique des schémas de fin de gestion | ANACO
<% end %>
<main role="main" class="containtAll">
  <div class="fr-container">
    <div class="fr-grid-row fr-grid-row--gutters">
      <div class="fr-col-12 fr-col-lg-12">
        <h1 class="fr-mt-6w fr-mb-2w ">Historique des propositions de contribution au schéma fin de gestion</h1>

        <div class="fr-table--lg fr-table fr-table--no-caption fr-mb-6w">
          <div class="fr-table__header">
            <p class="fr-table__detail"></p>
            <ul class="fr-btns-group fr-btns-group--right fr-btns-group--inline-md fr-btns-group--icon-left">
              <li>
                <button class="fr-btn fr-icon-filter-line fr-btn--icon-left " aria-controls="filtres" aria-expanded="false">Filtrer
                  les
                  résultats
                </button>
              </li>
            </ul>
          </div>
          <div class="fr-collapse fr-collapse--grey fr-px-2w" id="filtres" data-controller="request">
            <div class="fr-h4 fr-my-2w">Filtrer les résultats</div>
            <%= search_form_for @q, data: { 'request-target': 'form', turbo_frame: 'table', turbo_action: 'advance' } do |f| %>
              <div class="fr-grid-row fr-grid-row--gutters">
                <div class="fr-col-4">
                  <%= render_select_group("Programme", :programme_numero_in, Programme.all.order(numero: :asc).map {|p| p.numero}) %>
                </div>
                <div class="fr-col-4">
                  <%= render_tag_group 'Année', :annee_in, (2024..Date.today.year).to_a.map(&:to_s) %>
                </div>
              </div>
            <% end %>
          </div>
          <%= turbo_frame_tag :table, data: { turbo_action: 'advance' } do %>
            <div class="fr-table__wrapper">
              <div class="fr-table__container">
                <div class="fr-table__content">
                  <table class="fr-cell--multiline">
                    <caption>Historique des schémas fin de gestion</caption>
                    <thead>
                    <tr>
                      <th scope="col">
                        <% sort_created_date = "" %>
                        <% if params[:q] && params[:q][:s] == "updated_at desc" %>
                          <% sort_created_date = "asc" %>
                        <% elsif params[:q] && params[:q][:s] == "updated_at asc" %>
                          <% sort_created_date = "desc" %>
                        <% end %>
                        <div class="fr-cell--sort">
                          <span class="fr-cell__title">Date de saisie</span>
                          <%= sort_link(@q, :updated_at, '', default_order: :desc, class: 'fr-btn--sort fr-btn fr-btn--sm', aria: { sorting: sort_created_date }) %>
                        </div>
                      </th>
                      <th scope="col">Programme</th>
                      <th scope="col">Année</th>
                      <th scope="col">Version</th>
                      <th scope="col">Besoin de financement final selon RPROG</th>
                      <th scope="col">Besoin de financement final selon CBCM</th>
                      <th scope="col">Action</th>
                      <% if current_user.statut == "DCB" %>
                        <th scope="col"></th>
                      <% end %>
                    </tr>

                    </thead>


                    <tbody>
                    <% @schemas_page&.each do |schema| %>
                      <% gestion_schemas = schema.gestion_schemas %>
                      <% vision_rprog_ht2 = find_gestion_schema_vision(gestion_schemas, "RPROG", "HT2") %>
                      <% vision_rprog_t2 = find_gestion_schema_vision(gestion_schemas, "RPROG", "T2")  %>
                      <% vision_cbcm_ht2 = find_gestion_schema_vision(gestion_schemas, "CBCM", "HT2") %>
                      <% vision_cbcm_t2 = find_gestion_schema_vision(gestion_schemas, "CBCM", "T2")  %>
                      <tr>
                        <td><%= l(schema.updated_at, format: "%e/%m/%y") %> </td>
                        <td><%= link_to programme_path(schema.programme), data: {turbo_frame: '_top'} do %><%= schema.programme.numero %> - <%= schema.programme.nom %><%end %></td>
                        <td><%= schema.annee %>  </td>
                        <td>Version n°<%= numero_version(schema) %></td>
                        <td>
                          <% if vision_rprog_ht2&.solde_total_ae&.negative? %><p class="fr-badge fr-badge--warning">AE</p><% end %>
                          <% if vision_rprog_ht2&.solde_total_cp&.negative? %><p class="fr-badge fr-badge--warning">CP</p><% end %>
                          <% if vision_rprog_t2&.solde_total_ae&.negative? %><p class="fr-badge fr-badge--warning">HCAS</p><% end %>
                          <% if vision_rprog_t2&.solde_total_cp&.negative? %><p class="fr-badge fr-badge--warning">CAS</p><% end %>
                          <% if !vision_rprog_ht2&.solde_total_ae&.negative? && !vision_rprog_ht2&.solde_total_cp&.negative? && !vision_rprog_t2&.solde_total_ae&.negative? && !vision_rprog_t2&.solde_total_cp&.negative? %>
                            <p class="fr-badge fr-badge--success fr-badge--no-icon">Aucun</p>
                          <% end %>
                        </td>
                        <td>
                          <% if vision_cbcm_ht2&.solde_total_ae&.negative? %><p class="fr-badge fr-badge--warning">AE</p><% end %>
                          <% if vision_cbcm_ht2&.solde_total_cp&.negative? %><p class="fr-badge fr-badge--warning">CP</p><% end %>
                          <% if vision_cbcm_t2&.solde_total_ae&.negative? %><p class="fr-badge fr-badge--warning">HCAS</p><% end %>
                          <% if vision_cbcm_t2&.solde_total_cp&.negative? %><p class="fr-badge fr-badge--warning">CAS</p><% end %>
                          <% if !vision_cbcm_ht2&.solde_total_ae&.negative? && !vision_cbcm_ht2&.solde_total_cp&.negative? && !vision_cbcm_t2&.solde_total_ae&.negative? && !vision_cbcm_t2&.solde_total_cp&.negative? %>
                            <p class="fr-badge fr-badge--success fr-badge--no-icon">Aucun</p>
                          <% end %>
                        </td>
                        <td>
                          <% if schema.incomplete? && schema.user == current_user %>
                            <%= link_to new_schema_gestion_schema_path(schema), class: "fr-btn fr-btn--secondary", data: { turbo_frame: "_top" } do %>
                              Reprendre le brouillon
                            <% end %>
                          <% elsif schema.complete? %>
                            <a href="<%= schema_path(schema) %>" data-turbo-frame="modal" class="fr-btn fr-btn--secondary" data-fr-opened="false" aria-controls="fr-modal-2">
                              Consulter
                            </a>
                          <% end %>
                        </td>
                        <% if current_user.statut == "DCB" %>
                          <td>
                            <a href="<%= confirm_delete_schema_path(schema) %>" data-turbo-frame="modal" class="fr-btn fr-btn--secondary fr-icon-delete-bin-line" data-fr-opened="false" aria-controls="fr-modal-2">
                              Supprimer
                            </a>
                          </td>
                        <% end %>
                      </tr>
                    <% end %>

                    </tbody>

                  </table>
                </div>
              </div>
            </div>
            <div class="fr-table__footer">
              <div class="fr-table__footer--start">
                <p class="fr-table__detail"><%= pluralize(@schemas.length, 'résultat', plural: 'résultats') %></p>
                <div class="fr-select-group">
                  <label class="fr-sr-only fr-label" for="table-footer-select-7847">
                    Nombre de lignes par page
                  </label>
                  <div class="fr-messages-group" id="table-footer-select-7847-messages" aria-live="polite"></div>
                </div>
              </div>
              <div class="fr-table__footer--middle">
                <%== pagy_nav_custom(@pagy) %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <dialog aria-labelledby="fr-modal-2-title" id="fr-modal-2" class="fr-modal" role="dialog">
    <%= turbo_frame_tag :modal, target: "_top" %>
  </dialog>
</main>

app/views/schemas/pdf_vision.html.erb
<div class="fr-container fr-container--fluid fr-container-md">
  <h1 class="fr-mt-6w fr-mb-2w">
    Schéma de fin de gestion du programme n°<%= @schema.programme.numero %>
  </h1>
  <div class="fr-text--italic fr-text--light fr-my-2w">Version du <%= l(@schema.updated_at, format: "%e/%m/%y") %></div>
  <% if find_gestion_schema_vision(@gestion_schemas, "RPROG", "HT2")  %>
    <h2 class="fr-mb-1w">Vision HT2</h2>
    <%= render partial: 'show_vision', locals: { vision: "HT2", vision_rprog: find_gestion_schema_vision(@gestion_schemas, "RPROG", "HT2") , vision_cbcm: find_gestion_schema_vision(@gestion_schemas, "CBCM", "HT2")  } %>
  <% end %>
  <% if find_gestion_schema_vision(@gestion_schemas, "RPROG", "T2")  %>
    <h2 class="fr-mb-1w">Vision T2</h2>
    <%= render partial: 'show_vision', locals: { vision: "T2", vision_rprog: find_gestion_schema_vision(@gestion_schemas, "RPROG", "T2") , vision_cbcm: find_gestion_schema_vision(@gestion_schemas, "CBCM", "T2")  } %>
  <% end %>
</div>

app/views/schemas/schemas_remplissage.html.erb
<div class="fr-container">
  <div class="fr-grid-row fr-grid-row--gutters">
    <div class="fr-col-12 fr-col-lg-12">
      <h1 class="fr-my-6w fr-mb-2w ">Remplissage des schémas de fin de gestion</h1>

      <div class="fr-alert fr-alert--info fr-mb-2w">
        <h3 class="fr-alert__title">Le bouton "Rédiger une nouvelle version" vous permet de créer un schéma de fin de gestion ou bien de le mettre à jour tout en gardant un historique des versions antérieures si elles existent.</h3>
      </div>
      <div class="fr-mb-4w">
        <div class="fr-card">
          <div class="fr-card__body">
            <div class="fr-card__content">
              <h3 class="fr-card__title">Il vous
                reste <%= pluralize(@programmes.count - current_user.programmes_with_schemas(@annee_a_afficher), 'proposition', plural: 'propositions') %>
                de contribution au schéma fin de gestion <%= @annee_a_afficher %> à rédiger</h3>
              <div class="fr-card__desc">
                <% @programmes&.each do |programme| %>
                  <div class="fr-grid-row fr-grid-row--gutters fr-grid-row--middle">
                    <div class="fr-col-lg-2 fr-col-12">
                      <ul>
                        <li><%= link_to programme_path(programme) do %>Programme n°<%= programme.numero %><% end %></li>
                      </ul>
                    </div>
                    <div class="fr-col-lg-3 fr-col-4">
                      <% if programme.last_schema(@annee_a_afficher).nil? || programme.gestion_schemas.where(annee: @annee_a_afficher).empty? %>
                        <p class="fr-badge fr-badge--warning fr-badge--no-icon">
                          <span class="fr-icon-edit-fill fr-icon--sm" aria-hidden="true"></span> Schema fin de gestion
                        </p>
                      <% elsif programme.last_schema(@annee_a_afficher)&.complete? || programme.last_schema(@annee_a_afficher)&.gestion_schemas_empty? %>
                        <p class="fr-badge fr-badge--info fr-badge--no-icon">
                          Version n°<%= numero_version(programme.last_schema_valid(@annee_a_afficher)) %>
                          du <%= programme.last_schema_valid(@annee_a_afficher).created_at.strftime("%d/%-m/%Y") %>
                        </p>
                      <% elsif programme.last_schema(@annee_a_afficher)&.incomplete? %>
                        <p class="fr-badge fr-badge--new fr-badge--no-icon">Brouillon version
                          n°<%= numero_version(programme.last_schema(@annee_a_afficher)) %></p>
                      <% end %>
                    </div>
                    <div class="fr-col-lg-3 fr-col-4">
                      <% if programme.last_schema(@annee_a_afficher).nil? || programme.last_schema(@annee_a_afficher)&.complete? %>
                        <%= link_to programme_schemas_path(programme.id), data: { 'turbo_method': :post }, class: "fr-btn #{'fr-btn--secondary' if programme.last_schema(@annee_a_afficher)&.complete?}" do %>
                          Rédiger une nouvelle version
                        <% end %>
                      <% else %>
                        <%= link_to new_schema_gestion_schema_path(programme.last_schema(@annee_a_afficher)), class: "fr-btn #{'fr-btn--secondary' if !programme.gestion_schemas_empty? && programme.last_schema(@annee_a_afficher)&.gestion_schemas_empty?}" do %>
                          <%= programme.last_schema(@annee_a_afficher)&.incomplete? ? "Reprendre le
                          brouillon" : "Rédiger une nouvelle version" %>
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>